In [3]:
import os, os.path
import numpy as np
from keras.preprocessing import image
import cv2
import re

from PIL import Image
import pytesseract as pt 
import pandas as pd 

# Import Keras for CNN model,
from keras.models import Sequential
from keras.layers import Conv2D
from keras.layers import MaxPooling2D
from keras.layers import Flatten
from keras.layers import Dense
from keras.preprocessing.image import ImageDataGenerator

In [25]:
# Initialising the CNN
cnnmodel = Sequential()

cnnmodel.add(Conv2D(32, (3, 3), input_shape = (64, 64, 3), activation = 'relu'))
cnnmodel.add(MaxPooling2D(pool_size = (2, 2)))

cnnmodel.add(Conv2D(32, (3, 3), activation = 'relu'))
cnnmodel.add(MaxPooling2D(pool_size = (2, 2)))
   
cnnmodel.add(Flatten())    
 
cnnmodel.add(Dense(units = 128, activation = 'relu'))
cnnmodel.add(Dense(units = 3, activation = 'softmax'))

cnnmodel.compile(optimizer = 'rmsprop', loss = 'sparse_categorical_crossentropy', metrics = ['accuracy'])

In [6]:
os.getcwd()

'C:\\Users\\50316\\Downloads\\EAI6020final'

In [26]:
train_gen = ImageDataGenerator(rescale = 1./255,
                               shear_range = 0.1,
                               zoom_range = 0.1,
                               horizontal_flip = True)

test_gen = ImageDataGenerator(rescale = 1./255)

train_set = train_gen.flow_from_directory('train_image',
                                           target_size = (64, 64),
                                           batch_size = 4,
                                           class_mode = 'binary')

test_set = test_gen.flow_from_directory('test_image',
                                         target_size = (64, 64),
                                         batch_size = 4,
                                         class_mode = 'binary')

Found 84 images belonging to 3 classes.
Found 36 images belonging to 3 classes.


In [27]:
cnnmodel.fit(train_set,
             steps_per_epoch = 21,
             epochs = 50,
             validation_data = test_set,
             validation_steps = 3)

accuracy = cnnmodel.evaluate_generator(test_set, 100)

print('Accuracy of the model: ', accuracy)

Epoch 1/50
21/21 [==============================] - 1s 35ms/step - loss: 1.4779 - accuracy: 0.3694 - val_loss: 0.5124 - val_accuracy: 0.8333
Epoch 2/50
21/21 [==============================] - 0s 23ms/step - loss: 0.9934 - accuracy: 0.5454 - val_loss: 1.0948 - val_accuracy: 0.4167
Epoch 3/50
21/21 [==============================] - 0s 22ms/step - loss: 0.6085 - accuracy: 0.7629 - val_loss: 0.4263 - val_accuracy: 0.7500
Epoch 4/50
21/21 [==============================] - 0s 22ms/step - loss: 0.4383 - accuracy: 0.8790 - val_loss: 0.1288 - val_accuracy: 0.9167
Epoch 5/50
21/21 [==============================] - 0s 23ms/step - loss: 0.2926 - accuracy: 0.8421 - val_loss: 0.4110 - val_accuracy: 0.8333
Epoch 6/50
21/21 [==============================] - 0s 22ms/step - loss: 0.1763 - accuracy: 0.9347 - val_loss: 0.0209 - val_accuracy: 1.0000
Epoch 7/50
21/21 [==============================] - 0s 22ms/step - loss: 0.1690 - accuracy: 0.9426 - val_loss: 0.0042 - val_accuracy: 1.0000
Epoch 8/50
21

C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\keras\engine\training.py:1877: UserWarning: `Model.evaluate_generator` is deprecated and will be removed in a future version. Please use `Model.evaluate`, which supports generators.
  warnings.warn('`Model.evaluate_generator` is deprecated and '


In [28]:
from keras.preprocessing import image
train_set.class_indices

{'form1': 0, 'form2': 1, 'form3': 2}

In [29]:
import pytesseract
pytesseract.pytesseract.tesseract_cmd = r'C:\\Program Files\\Tesseract-OCR\\tesseract.exe'

In [14]:
imageDir = ("C:\\Users\\50316\\Downloads\\EAI6020final\\allimage")
image_path_list = []
valid_image_extensions = [".jpg"] 
#specify your vald extensions here
valid_image_extensions = [item.lower() for item in valid_image_extensions]

for file in os.listdir(imageDir):
    extension = os.path.splitext(file)[1]
    if extension.lower() not in valid_image_extensions:
        continue
    image_path_list.append(os.path.join(imageDir, file))

In [15]:
data=pd.DataFrame(index=np.arange(100),columns=['decedent','date','section','lot','grave','Filename'])

In [30]:
images = []
for imagePath in image_path_list:

    image_re = cv2.imread(imagePath)
    images.append(image_re)
    test_image = image.load_img(imagePath, target_size = (64, 64))
    test_image = image.img_to_array(test_image)
    test_image = np.expand_dims(test_image, axis = 0)
    pred = cnnmodel.predict(test_image)
    print(test_image.shape)
    print(pred)
print(images[0].shape)

(1, 64, 64, 3)
[[1. 0. 0.]]
(1, 64, 64, 3)
[[1. 0. 0.]]
(1, 64, 64, 3)
[[1. 0. 0.]]
(1, 64, 64, 3)
[[1. 0. 0.]]
(1, 64, 64, 3)
[[1. 0. 0.]]
(1, 64, 64, 3)
[[1. 0. 0.]]
(1, 64, 64, 3)
[[1. 0. 0.]]
(1, 64, 64, 3)
[[0. 0. 1.]]
(1, 64, 64, 3)
[[1. 0. 0.]]
(1, 64, 64, 3)
[[0. 0. 1.]]
(1, 64, 64, 3)
[[1. 0. 0.]]
(1, 64, 64, 3)
[[1. 0. 0.]]
(1, 64, 64, 3)
[[1. 0. 0.]]
(1, 64, 64, 3)
[[1. 0. 0.]]
(1, 64, 64, 3)
[[0. 0. 1.]]
(1, 64, 64, 3)
[[1. 0. 0.]]
(1, 64, 64, 3)
[[1. 0. 0.]]
(1, 64, 64, 3)
[[1. 0. 0.]]
(1, 64, 64, 3)
[[1. 0. 0.]]
(1, 64, 64, 3)
[[1. 0. 0.]]
(1, 64, 64, 3)
[[0. 1. 0.]]
(1, 64, 64, 3)
[[0. 1. 0.]]
(1, 64, 64, 3)
[[0. 0. 1.]]
(1, 64, 64, 3)
[[0. 0. 1.]]
(1, 64, 64, 3)
[[0. 0. 1.]]
(1, 64, 64, 3)
[[1. 0. 0.]]
(1, 64, 64, 3)
[[0. 1. 0.]]
(1, 64, 64, 3)
[[1. 0. 0.]]
(1, 64, 64, 3)
[[0. 0. 1.]]
(1, 64, 64, 3)
[[0. 0. 1.]]
(1, 64, 64, 3)
[[0. 0. 1.]]
(1, 64, 64, 3)
[[0. 0. 1.]]
(1, 64, 64, 3)
[[0. 0. 1.]]
(1, 64, 64, 3)
[[0. 1. 0.]]
(1, 64, 64, 3)
[[1. 0. 0.]]
(1, 64, 64, 3)
[[0. 

In [31]:
for i in images:
    print (i.shape)

(592, 987, 3)
(591, 986, 3)
(592, 987, 3)
(590, 984, 3)
(588, 988, 3)
(590, 986, 3)
(588, 987, 3)
(583, 971, 3)
(592, 988, 3)
(583, 971, 3)
(590, 987, 3)
(592, 986, 3)
(587, 984, 3)
(591, 992, 3)
(594, 976, 3)
(591, 990, 3)
(592, 988, 3)
(594, 990, 3)
(591, 991, 3)
(592, 990, 3)
(598, 986, 3)
(592, 992, 3)
(591, 970, 3)
(592, 978, 3)
(595, 978, 3)
(590, 988, 3)
(595, 988, 3)
(588, 987, 3)
(586, 974, 3)
(584, 988, 3)
(584, 974, 3)
(583, 974, 3)
(594, 978, 3)
(591, 994, 3)
(590, 990, 3)
(594, 976, 3)
(587, 987, 3)
(592, 988, 3)
(594, 991, 3)
(592, 976, 3)
(592, 987, 3)
(590, 1119, 3)
(591, 975, 3)
(584, 978, 3)
(596, 986, 3)
(583, 975, 3)
(587, 988, 3)
(590, 990, 3)
(592, 992, 3)
(595, 978, 3)
(595, 990, 3)
(588, 988, 3)
(592, 988, 3)
(584, 974, 3)
(588, 992, 3)
(591, 990, 3)
(595, 976, 3)
(590, 988, 3)
(595, 990, 3)
(591, 992, 3)
(591, 992, 3)
(595, 988, 3)
(590, 992, 3)
(600, 990, 3)
(594, 991, 3)
(594, 976, 3)
(588, 991, 3)
(595, 991, 3)
(584, 975, 3)
(594, 990, 3)
(591, 979, 3)
(592,

In [32]:
# Process images by classifications
def form1process(image,a):
    print("This is a form 1 image")
    image = cv2.resize(image,(900,500))
    cv2.imwrite("C:\\Users\\50316\\Downloads\\EAI6020final\\processing\\form1\\image_%d.jpg"%a,image)
    
    image = image[0:150,]
    cv2.imwrite("C:\\Users\\50316\\Downloads\\EAI6020final\\processing\\form1\\cropped_%d.jpg"%a,image)
    
    image = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
    cv2.imwrite("C:\\Users\\50316\\Downloads\\EAI6020final\\processing\\form1\\grayscaled_%d.jpg"%a,image)
    
    image = cv2.resize(image, None, fx=2, fy=2, interpolation=cv2.INTER_CUBIC)
    image = cv2.fastNlMeansDenoising(image, None, 10, 7, 21)
    kernel = np.ones((1,1), np.uint8)
    image = cv2.erode(image, kernel, iterations=1)
    image = cv2.dilate(image, kernel, iterations=1)
    
    
    image = cv2.adaptiveThreshold(cv2.GaussianBlur(image, (1, 1), 0), 255, cv2.ADAPTIVE_THRESH_GAUSSIAN_C, cv2.THRESH_BINARY, 31, 2)
    cv2.imwrite("C:\\Users\\50316\\Downloads\\EAI6020final\\processed\\processedf1_%d.jpg"%a,image)
    print("the shape of processed image:",image.shape)
    
    return image    

def form2process(image,b):
    print("This is a form 2 image")
    image = cv2.resize(image,(900,500))
    cv2.imwrite("C:\\Users\\50316\\Downloads\\EAI6020final\\processing\\form2\\image_%d.jpg"%b,image)
    
    image = image[10:200,0:810]
    cv2.imwrite("C:\\Users\\50316\\Downloads\\EAI6020final\\processing\\form2\\cropped_%d.jpg"%b,image)
    
    image = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
    cv2.imwrite("C:\\Users\\50316\\Downloads\\EAI6020final\\processing\\form2\\grayscaled_%d.jpg"%b,image)
    
    image = cv2.resize(image_placeholder, None, fx=2, fy=2, interpolation=cv2.INTER_CUBIC)
    image = cv2.fastNlMeansDenoising(image, None, 10, 7, 21)
    kernel = np.ones((1,1), np.uint8)
    image = cv2.erode(image, kernel, iterations=1)
    image = cv2.dilate(image, kernel, iterations=1)
    
    
    image = cv2.adaptiveThreshold(cv2.GaussianBlur(image, (1, 1), 0), 255, cv2.ADAPTIVE_THRESH_GAUSSIAN_C, cv2.THRESH_BINARY, 31, 2) 
    cv2.imwrite("C:\\Users\\50316\\Downloads\\EAI6020final\\processed\\processedf2_%d.jpg"%b,image)
    print("the shape of processed image:",image.shape)
    
    return image

def form3process(image,c):
    print("This is a form 3 image")
    image = cv2.resize(image,(900,500))
    cv2.imwrite("C:\\Users\\50316\\Downloads\\EAI6020final\\processing\\form3\\image_%d.jpg"%c,image)

    image = image[10:200,0:810]
    cv2.imwrite("C:\\Users\\50316\\Downloads\\EAI6020final\\processing\\form3\\cropped_%d.jpg"%c,image)
    
    image = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
    cv2.imwrite("C:\\Users\\50316\\Downloads\\EAI6020final\\processing\\form3\\grayscaled_%d.jpg"%c,image_placeholder)
    
    image = cv2.resize(image, None, fx=2, fy=2, interpolation=cv2.INTER_CUBIC)
    image = cv2.fastNlMeansDenoising(image, None, 10, 7, 21)
    kernel = np.ones((1,1), np.uint8)
    image = cv2.erode(image, kernel, iterations=1)
    image = cv2.dilate(image, kernel, iterations=1)  
    
    image = cv2.adaptiveThreshold(cv2.GaussianBlur(image, (1, 1), 0), 255, cv2.ADAPTIVE_THRESH_GAUSSIAN_C, cv2.THRESH_BINARY, 31, 2)
    cv2.imwrite("C:\\Users\\50316\\Downloads\\EAI6020final\\processed\\processedf3_%d.jpg"%c,image)
    print("the shape of processed image:", image.shape)
    
    return image

In [33]:
# Cut needed blocks for different information by ratios\n",
def imacrop(type,attribute,image):
    height,width = image.shape[:2]
    
    if(type=='f1'):
        if(attribute=='decedent'):
            startrow,startcol = int(height*0.1923),int(width *0.01)
            endrow,endcol = int(height *0.67),int(width *0.6591)            
            return image[startrow:endrow,startcol:endcol]
        
        elif(attribute=='date'):
            startrow,startcol = int(height*0.67307),int(width * 0.01)
            endrow,endcol = int(height * 0.99),int(width *0.2958)            
            return image[startrow:endrow,startcol:endcol]           
        
        elif(attribute=='section'):
            startrow,startcol = int(height*0.67307),int(width * 0.344)
            endrow,endcol = int(height *0.99 ),int(width *0.44)            
            return image[startrow:endrow,startcol:endcol]            
        
        elif(attribute=='lot'):
            startrow,startcol = int(height*0.67307),int(width * 0.4534)
            endrow,endcol = int(height *0.99),int(width *0.569)            
            return image[startrow:endrow,startcol:endcol]
        
        elif(attribute=='grave'):
            startrow,startcol = int(height*0.67307),int(width *0.627 )
            endrow,endcol = int(height * 0.99),int(width *0.6913)            
            return image[startrow:endrow,startcol:endcol]
        
    elif(type=='f2'):
        if(attribute=='decedent'):
            startrow,startcol = int(height*0.01),int(width *0.1136)
            endrow,endcol = int(height *0.306),int(width *0.99)            
            return image[startrow:endrow,startcol:endcol]
    
        elif(attribute=='date'):
            startrow,startcol = int(height*0.7551),int(width * 0.19)
            endrow,endcol = int(height * 0.99),int(width *0.99)            
            return image[startrow:endrow,startcol:endcol]           
        
        elif(attribute=='section'):
            startrow,startcol = int(height*0.306),int(width * 0.647)
            endrow,endcol = int(height *0.51 ),int(width *0.99)            
            return image[startrow:endrow,startcol:endcol]           
        
        elif(attribute=='lot'):
            startrow,startcol = int(height*0.306),int(width * 0.1136)
            endrow,endcol = int(height *0.51 ),int(width *0.4525)            
            return image[startrow:endrow,startcol:endcol]
        
        elif(attribute=='grave'):
            startrow,startcol = int(height*0.51),int(width *0.1136)
            endrow,endcol = int(height * 0.7551),int(width *0.4525)            
            return image[startrow:endrow,startcol:endcol]
        
    elif(type=='f3'):
        if(attribute=='decedent'):
            startrow,startcol = int(height*0.001),int(width *0.0935)
            endrow,endcol = int(height *0.3857),int(width *0.9)            
            return image[startrow:endrow,startcol:endcol]
        
        elif(attribute=='date'):
            startrow,startcol = int(height*0.85714),int(width * 0.1613)
            endrow,endcol = int(height * 0.99),int(width *0.9)            
            return image[startrow:endrow,startcol:endcol]           
       
        elif(attribute=='section'):
            startrow,startcol = int(height*0.3857),int(width * 0.5806)
            endrow,endcol = int(height *0.6 ),int(width *0.9)           
            return image[startrow:endrow,startcol:endcol]            
     
        elif(attribute=='lot'):
            startrow,startcol = int(height*0.3857),int(width * 0.0935)
            endrow,endcol = int(height *0.6 ),int(width *0.4516)            
            return image[startrow:endrow,startcol:endcol]
      
        elif(attribute=='grave'):
            startrow,startcol = int(height*0.6),int(width *0.0935 )
            endrow,endcol = int(height * 0.85),int(width *0.4516)            
            return image[startrow:endrow,startcol:endcol]

In [34]:
# Counters Initialization
a=b=c=0
row_counter=0
# Read through every images
for imagePath in image_path_list:
    image_red = cv2.imread(imagePath)
    test_image = image.load_img(imagePath, target_size = (64, 64))
    test_image = image.img_to_array(test_image)
    test_image = np.expand_dims(test_image, axis = 0)
    result = cnnmodel.predict(test_image)
    print(result)

    #For Form 1 images:    
    if result[0][0]==1:
        
        image_placeholder = form1process(image_red,a)

        f1_decedent = pt.image_to_string(imacrop('f1','decedent',image_placeholder), lang ='eng')
        f1_decedent = re.sub('[^A-Za-z0-9]+',' ', f1_decedent)
        f1_decedent = f1_decedent.replace('DECEDENT','')
        f1_decedent = f1_decedent.replace('DECEASED','')
        print("Decedent %s" % (f1_decedent))
 
        f1_date = pt.image_to_string(imacrop('f1','date',image_placeholder), lang ="eng")
        f1_date = f1_date.replace('\n','')
        print("Date %s" % (f1_date))
 
        f1_section = pt.image_to_string(imacrop('f1','section',image_placeholder), lang ="eng")
        f1_section = re.sub('[A-Za-z$&+,:;=?@#|\'<>.^*()%!-]+','',f1_section)
        f1_section = f1_section.strip()
        f1_section = f1_section.replace('\n','')
        print("Section %s" % (f1_section))
 
        f1_lot = pt.image_to_string(imacrop('f1','lot',image_placeholder), lang ="eng")
        f1_lot = f1_lot.replace('\n','')
        f1_lot = re.sub('[^A-Za-z0-9]+',' ', f1_lot)
        print("Lot %s" % (f1_lot))
    
        f1_grave = pt.image_to_string(imacrop('f1','grave',image_placeholder), lang ="eng")
        f1_grave = re.sub('[^0-9]+',' ', f1_grave)
        f1_grave = f1_grave.replace('\n','')
        print("Grave %s" % (f1_grave))
    
        # DataFrame write
        data.loc[row_counter]=pd.Series({'decedent':f1_decedent, 'date':f1_date, 'section':f1_section, 'lot':f1_lot,'grave':f1_grave, 'Filename': imagePath[-26:]})
   
        row_counter+=1
        a+=1

    elif result[0][1]==1:

        image_placeholder = form2process(image_red,b)

        f2_decedent = pt.image_to_string(imacrop('f2','decedent',image_placeholder), lang ='eng')
        f2_decedent = re.sub('[^A-Za-z0-9]+', ' ', f2_decedent)
        print("Decedent %s" % (f2_decedent))

        f2_date = pt.image_to_string(imacrop('f2','date',image_placeholder), lang ="eng")
        f2_date = f2_date.replace('\n','')
        print("Date %s" % (f2_date))

        f2_section = pt.image_to_string(imacrop('f2','section',image_placeholder), lang ="eng")
        f2_section = re.sub('[A-Za-z$&+,:;=?@#|\'<>.^*()%!-]+','',f2_section)
        f2_section = f2_section.strip()
        f2_section = f2_section.replace('\n','')
        print("Section %s" % (f2_section))
  
        f2_lot = pt.image_to_string(imacrop('f2','lot',image_placeholder), lang ="eng")
        f2_lot = re.sub('[^A-Za-z0-9]+',' ', f2_lot)
        f2_lot = f2_lot.replace('\\n','')
        print("Lot %s" % (f2_lot))
   
        f2_grave = pt.image_to_string(imacrop('f2','grave',image_placeholder), lang ="eng")
        f2_grave = f2_grave.replace('\n','')
        f2_grave = re.sub('[^0-9]+',' ', f2_grave)
        print("Grave %s" % (f2_grave))

        # DataFrame write\n",
        data.loc[row_counter]=pd.Series({'decedent':f2_decedent, 'date':f2_date, 'section':f2_section, 'lot':f2_lot,'grave':f2_grave, 'Filename': imagePath[-26:]})
   
        row_counter+=1 
        b+=1
    
    elif result[0][2]==1:
    
        image_placeholder = form3process(image_red,c)
   
        f3_decedent = pt.image_to_string(imacrop('f3','decedent',image_placeholder), lang ="eng")
        f3_decedent = re.sub('[^A-Za-z0-9]+', ' ', f3_decedent)
        print("Decedent %s" % (f3_decedent))
 
        f3_date = pt.image_to_string(imacrop('f3','date',image_placeholder), lang ="eng")
        f3_date = f3_date.replace('\n','')
        print("Date %s" % (f3_date))
  
        f3_section = pt.image_to_string(imacrop('f3','section',image_placeholder), lang ="eng")
        f3_section = re.sub('[A-Za-z$&+,:;=?@#|\'<>.^*()%!-]+','',f3_section)
        f3_section = f3_section.strip()
        f3_section = f3_section.replace('\n','')
        print("Section %s" % (f3_section))
        
        f3_lot = pt.image_to_string(imacrop('f3','lot',image_placeholder), lang ="eng")
        f3_lot = re.sub('[^A-Za-z0-9]+',' ', f3_lot)
        f3_lot = f3_lot.replace('\n','')
        print("Lot %s" % (f3_lot))
        
        f3_grave = pt.image_to_string(imacrop('f3','grave',image_placeholder), lang ="eng")
        f3_grave = re.sub('[^0-9]+',' ', f3_grave)
        f3_grave = f3_grave.replace('\n','')
        print("Grave %s" % (f3_grave))
        
        # DataFrame write\n",
        data.loc[row_counter]=pd.Series({'decedent':f3_decedent, 'date':f3_date, 'section':f3_section, 'lot':f3_lot,'grave':f3_grave, 'Filename': imagePath[-26:]})
        
        row_counter+=1        
        c+=1

[[1. 0. 0.]]
This is a form 1 image
the shape of processed image: (300, 1800)
Decedent  AGE DABA AYEHUSH H FEMALE RATS Re pes Yeo al 
Date bathe iat ih ie
Section 
Lot eee 
Grave  
[[1. 0. 0.]]
This is a form 1 image
the shape of processed image: (300, 1800)
Decedent DOICEASED DABA LEMANEE 
Date OATES GP WelEnesene6/24/96
Section 
Lot LW TER233RO0h 
Grave  
[[1. 0. 0.]]
This is a form 1 image
the shape of processed image: (300, 1800)
Decedent DABA SHORROQ DATE OF IMTERMENT SECTION LOT TER aa mranhnrnrarm on Mmmnamrmmind 
Date Ff 4tvgfgnu USDERTAKER
Section 
Lot  
Grave  
[[1. 0. 0.]]
This is a form 1 image
the shape of processed image: (300, 1800)
Decedent OICEASED DABE PATRICIA JEAN CREMAINS HATE OSs colt eestor ge cw 10T TER GR 
Date 
Section 
Lot  
Grave  10 
[[1. 0. 0.]]
This is a form 1 image
the shape of processed image: (300, 1800)
Decedent DACLAs D DABNEY ABRAHAM L 
Date RAIS VP I eee12/8/97
Section 28
Lot Swe rem 
Grave  
[[1. 0. 0.]]
This is a form 1 image
the shape of p

Date 
Section 
Lot  
Grave  
[[0. 1. 0.]]
This is a form 2 image
the shape of processed image: (1520, 6480)
Decedent atin Yietor 
Date 
Section 
Lot  
Grave  
[[0. 0. 1.]]
This is a form 3 image
the shape of processed image: (380, 1620)
Decedent  Dahike Reinhold 
Date nt “July 13, 1945
Section 
Lot NEt 190 
Grave  
[[0. 0. 1.]]
This is a form 3 image
the shape of processed image: (380, 1620)
Decedent Dahlman William 3 
Date Mareh 10 1919
Section 18
Lot Vis 87 
Grave  
[[0. 1. 0.]]
This is a form 2 image
the shape of processed image: (760, 3240)
Decedent Jahlman William HB 
Date farch 10 1919
Section 
Lot B87 
Grave  
[[0. 1. 0.]]
This is a form 2 image
the shape of processed image: (1520, 6480)
Decedent Jahlman William ZH 
Date farech 10 1919
Section 
Lot 31 Std 
Grave  
[[0. 0. 1.]]
This is a form 3 image
the shape of processed image: (380, 1620)
Decedent  Dahistrom t i RNC arr 
Date UCGe vy 12°40
Section 19
Lot EX 503 
Grave  
[[1. 0. 0.]]
This is a form 1 image
the shape of p

the shape of processed image: (380, 1620)
Decedent Daker Alfred 
Date Ust. 26, 1IS2
Section 36
Lot 132 
Grave  
[[0. 0. 1.]]
This is a form 3 image
the shape of processed image: (380, 1620)
Decedent Dater Taura 
Date Aprilow1910
Section 
Lot 105 
Grave  
[[0. 0. 1.]]
This is a form 3 image
the shape of processed image: (380, 1620)
Decedent baker Palzh 
Date vocemesr 1) Avid
Section 
Lot LOD 
Grave  
[[0. 0. 1.]]
This is a form 3 image
the shape of processed image: (380, 1620)
Decedent Daker Rapnael 
Date April 25.199
Section 15
Lot LOS 
Grave  
[[0. 0. 1.]]
This is a form 3 image
the shape of processed image: (380, 1620)
Decedent  
Date duLy LS, loc?
Section 
Lot 152 
Grave  
[[0. 0. 1.]]
This is a form 3 image
the shape of processed image: (380, 1620)
Decedent Daker Sareh 
Date 6s| ieswena
Section 
Lot 105 
Grave  3 3 
[[0. 0. 1.]]
This is a form 3 image
the shape of processed image: (380, 1620)
Decedent Lakin Evelyn i 
Date Karch 27, 1920
Section 18
Lot  
Grave  
[[0. 1. 0.]]


In [35]:
data

decedent  \
0        AGE DABA AYEHUSH H FEMALE RATS Re pes Yeo al    
1                              DOICEASED DABA LEMANEE    
2    DABA SHORROQ DATE OF IMTERMENT SECTION LOT TER...   
3    OICEASED DABE PATRICIA JEAN CREMAINS HATE OSs ...   
4                           DACLAs D DABNEY ABRAHAM L    
..                                                 ...   
115                                   cerrenmessT c10    
116  OfCLASID DALAS KATHELEEN GATE OF INTIRe MENT S...   
117                                 Dalbier Elizabeth    
118  DECLASED DAL DEGAN VAL BaloelmTenming Ss wen W...   
119                                              Cf 6    

                            date section             lot grave  \
0               bathe iat ih ie
                    eee          
1    OATES GP WelEnesene6/24/96
          LW TER233RO0h          
2        Ff 4tvgfgnu USDERTAKER
                                 
3                              
                           10    
4          RAIS VP I eee12/8/97
      28        Swe rem          
..                           ...     ...             ...   ...   
115          y LIOIDBBI1L)éNANA
          DAKO CAROLINE          
116                    6/6/2003
                  109 1          
117        oJ oOpvemoor 17 L910
       é            136          
118                   12/8/2003
                 i S1DE          
119                            
                                 

                       Filename  
0    21873_1_Daba_Ayehush_H.jpg  
1    _021874_1_Daba_Lemanee.jpg  
2    d_021875_1_Daba_Shorro.jpg  
3    6_1_Dabe_Patricia_Jean.jpg  
4    877_1_Dabney_Abraham_L.jpg  
..                          ...  
115  d_021988_1_Dako_Martha.jpg  
116  1989_1_Dalas_Katheleen.jpg  
117  90_1_DALBIER_ELIZABETH.jpg  
118  21991_1_Dail-Degan_Val.jpg  
119  021992_1_DALDORF_ALICE.jpg  

[120 rows x 6 columns]

In [36]:
data.to_csv(r'C:\\Users\\50316\\Downloads\\EAI6020final\\preprocess.csv', index=False)